#pragma once

#define POINTING_DEVICE_DEBUG

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
#define ANALOG_JOYSTICK_AUTO_AXIS true

#define LED_CAPS_LOCK_PIN GP25

// #define ANALOG_JOYSTICK_AXIS_MAX 512

// Lower Values Create Faster Movement
#define ANALOG_JOYSTICK_SPEED_REGULATOR 3
// #define MOUSE_EXTENDED_REPORT

#define MIDI_ADVANCED
